/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_describe_result$schema = z.object({
  'configured': z.boolean().readonly(),
  'source': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_logout_result$schema = z.void()
const _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_poll_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_poll_result$schema = z.union([z.object({
  'kind': z.literal("pending").readonly(),
}), z.object({
  'kind': z.literal("succeeded").readonly(),
}), z.object({
  'kind': z.literal("failed").readonly(),
  'message': z.string().readonly(),
}), z.object({
  'kind': z.literal("cancelled").readonly(),
})])
const _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_start_result$schema = z.object({
  'loginId': z.intersection(z.string(), z.unknown()).readonly(),
  'authorizationUrl': z.string().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-llm-pi-ai-antigravity',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-llm-pi-ai-antigravity#antiGravityAuth/describe',
      service: 'antiGravityAuth',
      namespace: 'antiGravityAuth',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm-pi-ai-antigravity/types#AntiGravityAuthSnapshot',
        schema: _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_describe_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm-pi-ai-antigravity/src/remote-service.ts","line":57,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-llm-pi-ai-antigravity#antiGravityAuth/logout',
      service: 'antiGravityAuth',
      namespace: 'antiGravityAuth',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm-pi-ai-antigravity#antiGravityAuth/logout:result',
        schema: _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_logout_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm-pi-ai-antigravity/src/remote-service.ts","line":115,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-llm-pi-ai-antigravity#antiGravityAuth/poll',
      service: 'antiGravityAuth',
      namespace: 'antiGravityAuth',
      method: 'poll',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-llm-pi-ai-antigravity/types#AntiGravityLoginId',
            schema: _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_poll_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm-pi-ai-antigravity/types#AntiGravityLoginStatus',
        schema: _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_poll_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm-pi-ai-antigravity/src/remote-service.ts","line":106,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-llm-pi-ai-antigravity#antiGravityAuth/start',
      service: 'antiGravityAuth',
      namespace: 'antiGravityAuth',
      method: 'start',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm-pi-ai-antigravity/types#AntiGravityLoginStart',
        schema: _deepseek_ai_dsh_llm_pi_ai_antigravity_antiGravityAuth_start_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm-pi-ai-antigravity/src/remote-service.ts","line":69,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
