/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AntiGravityAuthSnapshot, AntiGravityLoginId, AntiGravityLoginStart, AntiGravityLoginStatus } from '@deepseek-ai/dsh-llm-pi-ai-antigravity/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$616e74694772617669747941757468 {
    describe: () => Promise<RemoteResult<AntiGravityAuthSnapshot>>
    logout: () => Promise<RemoteResult<void>>
    poll: (id: AntiGravityLoginId) => Promise<RemoteResult<AntiGravityLoginStatus>>
    start: () => Promise<RemoteResult<AntiGravityLoginStart>>
  }
  interface TypertRemoteMap {
    'antiGravityAuth/describe': () => Promise<RemoteResult<AntiGravityAuthSnapshot>>
    'antiGravityAuth/logout': () => Promise<RemoteResult<void>>
    'antiGravityAuth/poll': (id: AntiGravityLoginId) => Promise<RemoteResult<AntiGravityLoginStatus>>
    'antiGravityAuth/start': () => Promise<RemoteResult<AntiGravityLoginStart>>
  }
  interface TypertRemoteNamespaceMap {
    'antiGravityAuth': TypertRemoteNamespace$616e74694772617669747941757468
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
